"""Exact prompt strings extracted from the original generation script."""

IDENTICAL_PROMPT = (
    'Generate exactly one image. The image must be a flat, front-facing, single-page document with pure '
    'white background.\n'
    'Render only plain paragraph text, styled like a LaTeX-typeset document.\n'
    'Layout constraints:\n'
    '- Single-column layout only\n'
    '- No multi-column or vertical splits\n'
    '- Text flows continuously from top to bottom\n'
    '\n'
    'Formatting constraints:\n'
    '- Paragraph text only\n'
    '- No titles, headings, lists, or equations\n'
    '- No indentation beyond normal paragraph spacing\n'
    '\n'
    'Do not include LaTeX source code or markup.\n'
    'Do not depict any real-world scene.\n'
    'The visible text must match the following text exactly.'
)
MULTILINGUAL_PROMPT = {'ar': (
    'أنشئ صورة واحدة فقط. يجب أن تكون الصورة مستندًا من صفحة واحدة، مسطحًا ومواجهًا للأمام، مع خلفية '
    'بيضاء بسيطة.\n'
    'اعرض نص فقرات فقط، منسقًا بصريًا ليشبه مستندًا مُنضَّدًا باستخدام LaTeX.\n'
    '\n'
    'قيود التخطيط:\n'
    'تخطيط بعمود واحد فقط\n'
    'عدم استخدام تخطيطات متعددة الأعمدة أو تقسيمات عمودية\n'
    'يتدفق النص بشكل متواصل من الأعلى إلى الأسفل\n'
    '\n'
    'قيود التنسيق:\n'
    'نص فقرات فقط\n'
    'عدم استخدام عناوين أو رؤوس أو قوائم أو معادلات\n'
    'عدم وجود مسافات بادئة تتجاوز تباعد الفقرات العادي\n'
    'لا تُدرج أي شيفرة مصدرية أو وسوم LaTeX.\n'
    'لا تُصوِّر أي مشهد من العالم الحقيقي.\n'
    'يجب أن يطابق النص الظاهر النص التالي تمامًا.'
), 'en': (
    'Generate exactly one image. The image must be a flat, front-facing, single-page document with pure '
    'white background.\n'
    'Render only plain paragraph text, styled like a LaTeX-typeset document.\n'
    'Layout constraints:\n'
    '- Single-column layout only\n'
    '- No multi-column or vertical splits\n'
    '- Text flows continuously from top to bottom\n'
    '\n'
    'Formatting constraints:\n'
    '- Paragraph text only\n'
    '- No titles, headings, lists, or equations\n'
    '- No indentation beyond normal paragraph spacing\n'
    '\n'
    'Do not include LaTeX source code or markup.\n'
    'Do not depict any real-world scene.\n'
    'The visible text must match the following text exactly'
), 'fr': (
    'Générez exactement une seule image. L’image doit être un document d’une seule page, plat et orienté '
    'de face, avec un fond blanc uni.\n'
    'Affichez uniquement du texte en paragraphes, présenté visuellement comme un document composé avec '
    'LaTeX.\n'
    '\n'
    'Contraintes de mise en page :\n'
    'Mise en page à une seule colonne\n'
    'Aucune mise en page multicolonne ni séparation verticale\n'
    'Le texte s’écoule continuellement de haut en bas\n'
    '\n'
    'Contraintes de formatage :\n'
    'Texte en paragraphes uniquement\n'
    'Aucun titre, en-tête, liste ou équation\n'
    'Aucune indentation au-delà de l’espacement normal entre les paragraphes\n'
    '\n'
    'N’incluez aucun code source ou balisage LaTeX.\n'
    'Ne représentez aucune scène du monde réel.\n'
    'Le texte visible doit correspondre exactement au texte suivant.'
), 'ja': (
    '画像を正確に1枚だけ生成してください。画像は、平坦で正面向きの単一ページの文書で、背景は無地の白とします。\n'
    'LaTeXで組版された文書の見た目になるように、段落形式のテキストのみを描画してください。\n'
    '\n'
    'レイアウト制約：\n'
    '単一カラムレイアウトのみ\n'
    '複数カラムや縦分割のレイアウトは禁止\n'
    'テキストは上から下へ連続して流れること\n'
    '\n'
    '書式制約：\n'
    '段落テキストのみ\n'
    'タイトル、見出し、リスト、数式は使用しない\n'
    '通常の段落間隔を超えるインデントは使用しない\n'
    '\n'
    'LaTeXのソースコードやマークアップは含めないでください。\n'
    '現実世界の場面は描写しないでください。\n'
    '表示されるテキストは、以下のテキストと完全に一致していなければなりません。'
), 'ko': (
    '이미지를 정확히 한 장만 생성하세요. 이미지는 평면적이고 정면을 향한 단일 페이지 문서여야 하며, 배경은 순수한 흰색이어야 합니다.\n'
    'LaTeX로 조판된 문서처럼 보이도록, 단락 형식의 텍스트만 렌더링하세요.\n'
    '\n'
    '레이아웃 제약:\n'
    '단일 열 레이아웃만 사용\n'
    '다중 열 또는 세로 분할 레이아웃 금지\n'
    '텍스트는 위에서 아래로 연속적으로 흐를 것\n'
    '\n'
    '서식 제약:\n'
    '단락 텍스트만 사용\n'
    '제목, 머리글, 목록, 수식 사용 금지\n'
    '일반적인 단락 간격을 넘는 들여쓰기 금지\n'
    '\n'
    'LaTeX 소스 코드나 마크업을 포함하지 마세요.\n'
    '현실 세계의 장면을 묘사하지 마세요.\n'
    '표시되는 텍스트는 다음 텍스트와 정확히 일치해야 합니다.'
), 'zh': (
    '仅生成一张图像。图像必须是平坦、正面朝向的单页文档，背景为纯白色。\n'
    '仅渲染段落文本，视觉风格应类似于 LaTeX 排版后的文档。\n'
    '\n'
    '布局约束：\n'
    '仅使用单栏布局\n'
    '不得使用多栏或纵向分割布局\n'
    '文本自上而下连续流动\n'
    '\n'
    '格式约束：\n'
    '仅使用段落文本\n'
    '不使用标题、页眉、列表或公式\n'
    '不使用超出正常段落间距的缩进\n'
    '\n'
    '不要包含任何 LaTeX 源代码或标记。\n'
    '不要描绘任何现实世界的场景。\n'
    '可见文本必须与以下文本完全一致。'
)}
REASONING_PROMPT = (
    'Return an image contains only the solution text, typeset to look like a LaTeX-compiled math '
    'solution. \n'
    'Render only plain paragraph text, styled as a single-column layout LaTeX-typeset document with pure '
    'white background. Do not depict any real-world scene.\n'
    '\n'
    'The solution text inside the image must follow the exact structure:\n'
    '- Each reasoning paragraph starts with "Step:".\n'
    '- The final paragraph is the answer with only one line exactly: "Answer: <final answer>".\n'
    '- <final answer> contains ONLY the final result itself, with no other variables, no equations, no '
    'units, no description, and no explanatory text.\n'
    '\n'
    'Return an image containing only the solution text.\n'
    'Question:\n'
)
CONTEXT_REASONING_PROMPT = (
    'You are answering a reading comprehension question using the given passage. \n'
    'Return exactly one image. The image must contain only the solution text.\n'
    'Render plain paragraph text only in a single-column layout with pure white background. Style the '
    'text to resemble a LaTeX-typeset document (compiled appearance, not source code). Do NOT depict any '
    'real-world scene.\n'
    '\n'
    'Solution requirements:\n'
    'Provide the reasoning first and then the final answer.\n'
    '- Each reasoning step must be one paragraph starting with "Reasoning:".\n'
    '- The final paragraph is one line, must start with exactly: "Answer: ".\n'
    '- After "Answer: ", output only the answer text.\n'
    '- If the answer has one span: output exactly that span.\n'
    '- If the answer has multiple spans: separate them with ", " (comma + single space).\n'
    '- If the answer requires arithmetic, output only the final number.\n'
    '- Otherwise, output one or more text spans copied verbatim from the passage.\n'
    'Return an image containing only the solution text.\n'
    '    '
)
MULTIPLE_CHOICE_PROMPT = (
    'You are answering a multiple choice question. \n'
    'Return exactly one image. The image must contain only the solution text.\n'
    'Render plain paragraph text only in a single-column layout with pure white background. Style the '
    'text to resemble a LaTeX-typeset document (compiled appearance, not source code). Do NOT depict any '
    'real-world scene.\n'
    '\n'
    'Solution requirements:\n'
    'Output only the reasoning steps and the final answer.\n'
    '- First output the reasoning and then the answer.\n'
    '- Provide exactly one reasoning paragraph for each choice.\n'
    '- Each reasoning step must be one paragraph starting with "Reasoning:".\n'
    '- The final paragraph is one line, must start with exactly: "Answer: <choice>".\n'
    '- The answer must be exactly only one capital letter: A, B, C, or D.\n'
    '- Do NOT include any other text after the answer line.\n'
    '\n'
    'Return an image containing only the solution text.\n'
    '    '
)
